# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashop',
            name='star',
            field=models.IntegerField(),
        ),
    ]
