# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20170921_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashop',
            name='star',
            field=models.FloatField(),
        ),
    ]
