# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]


