# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_dict_project_spider_spiderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
