# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 03:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_project_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dict',
            name='table',
        ),
    ]
