# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20170905_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderstatus',
            name='loc',
        ),
        migrations.AddField(
            model_name='spider',
            name='loc',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
