# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20170905_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderstatus',
            name='operation_time',
            field=models.CharField(max_length=20),
        ),
    ]
