# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20170905_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='spider',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
